# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_docker: # On Linux, iterates on all ROS 1, and ROS 2 distributions.
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ros_distribution:
          - eloquent

        # Define the Docker image(s) associated with each ROS distribution.
        # The include syntax allows additional variables to be defined, like
        # docker_image in this case. See documentation:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build
        #
        # Platforms are defined in REP 3, and REP 2000:
        # https://ros.org/reps/rep-0003.html
        # https://ros.org/reps/rep-2000.html
        include:
          # Eloquent Elusor (November 2019 - November 2020)
          - docker_image: ubuntu:bionic
            ros_distribution: eloquent
            ros_version: 2
            
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test ROS1
        if: ${{ matrix.ros_version == 1 }}
        uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: YOUR_PACKAGE_HERE MORE_PACKAGES_HERE
          target-ros1-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
      - name: build and test ROS2
        if: ${{ matrix.ros_version == 2 }}
        uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: plankton plankton_utils
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
   
  # This workflow contains a single job called "build"
  #build:
    # The type of runner that the job will run on
  #  runs-on: ubuntu-18.04
    
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: ros-tooling/setup-ros@0.0.25
  #      with:
  #        required-ros-distributions: eloquent
  #    - uses: ros-tooling/action-ros-ci@0.0.19
  #      with:
  #        package-name: plankton
  #        target-ros2-distro: eloquent
 

   
