# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_docker: # On Linux, iterates on all ROS 1, and ROS 2 distributions.
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ros_distribution:
          - eloquent

        # Define the Docker image(s) associated with each ROS distribution.
        # The include syntax allows additional variables to be defined, like
        # docker_image in this case. See documentation:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build
        #
        # Platforms are defined in REP 3, and REP 2000:
        # https://ros.org/reps/rep-0003.html
        # https://ros.org/reps/rep-2000.html
        include:
          # Eloquent Elusor (November 2019 - November 2020)
          - docker_image: ubuntu:bionic
            ros_distribution: eloquent
            ros_version: 2
            
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: prepare
        run: |
          apt-get -qq update
          apt-get -qq upgrade -y
          sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
          apt-get install gazebo9 -y
          apt-get install libgazebo9-dev -y
          apt install ros-eloquent-gazebo-ros-pkgs -y
          apt install ros-eloquent-launch-xml -y 
          apt install ros-eloquent-launch-yaml -y
          mkdir -p ros_ws/src
          
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src/
        
      - name: rosdep
        run: DEBIAN_FRONTEND=noninteractive rosdep update && rosdep install --from-paths ros_ws/src --ignore-src --rosdistro eloquent -y

      - name: build
        run: . /opt/ros/eloquent/setup.sh && colcon build --packages-up-to plankton --merge-install

      - name: run tests
        id: action_ros_ci_step
        run: . /opt/ros/eloquent/setup.sh && colcon test --merge-install --packages-up-to plankton --return-code-on-test-failure --event-handlers console_cohesion+
      
      - name: echo results
        run: . /opt/ros/eloquent/setup.sh  && colcon test-result --all --verbose
      
      - name: upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-linux
          path: log/
        if: always()
   
  # This workflow contains a single job called "build"
  #build:
    # The type of runner that the job will run on
  #  runs-on: ubuntu-18.04
    
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: ros-tooling/setup-ros@0.0.25
  #      with:
  #        required-ros-distributions: eloquent
  #    - uses: ros-tooling/action-ros-ci@0.0.19
  #      with:
  #        package-name: plankton
  #        target-ros2-distro: eloquent
 

   
